# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\Check_Cadet_2\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

# from OtherWindow import Ui_OtherWindow
from menu import Ui_MenwWindow
import mysql.connector

class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MenwWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 181, 19))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 50, 244, 116))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 0, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)    
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 2, 1, 1, 1)
   
        
        # self.login.clicked.connect(self.openWindow)
        self.login.clicked.connect(self.loginfunc)
        
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Please Login"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "username"))
        self.label_2.setText(_translate("MainWindow", "password"))
        
    def loginfunc(self):
        
        username = self.username.text()
        password = self.password.text()
        user(username, password, self)
        

def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="12341234",
        database="testdb",
        # auth_plugin='mysql_native_password'
    )
    # print('Connect Database Successful')
    return mydb

def user(username,password,self):
    print(password)
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT `pass` FROM `user` WHERE `user`="{username}"'
    cur.execute(sql)
    myresult = cur.fetchall()
    print(myresult)
    
    if myresult != []:
        x = str(myresult[0][0])
        passwd = password
        
        if passwd == x:
            print("login")
            self.openWindow()
        else:
            print("fail") 
            msg = QMessageBox()
            msg.setText('Incorrect Password')
            msg.exec_()
    else:
        msg = QMessageBox()
        msg.setText('Incorrect Password')
        msg.exec_()        
    return 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
