# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 30, 55, 16))
        self.title.setObjectName("title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 400, 631, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.com1_title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.com1_title.setObjectName("com1_title")
        self.verticalLayout.addWidget(self.com1_title)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.all1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.all1.setObjectName("all1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.all1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.active1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.active1.setObjectName("active1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.active1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.remain1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.remain1.setObjectName("remain1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remain1)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.com2_title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.com2_title.setObjectName("com2_title")
        self.verticalLayout_2.addWidget(self.com2_title)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.all2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.all2.setObjectName("all2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.all2)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.active2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.active2.setObjectName("active2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.active2)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.remain2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.remain2.setObjectName("remain2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remain2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.com3_title = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.com3_title.setObjectName("com3_title")
        self.verticalLayout_3.addWidget(self.com3_title)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.all3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.all3.setObjectName("all3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.all3)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.active3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.active3.setObjectName("active3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.active3)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.remain3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.remain3.setObjectName("remain3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remain3)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 240, 551, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sname_in = QtWidgets.QLabel(self.layoutWidget)
        self.sname_in.setObjectName("sname_in")
        self.gridLayout_2.addWidget(self.sname_in, 0, 2, 1, 1)
        self.uname_in = QtWidgets.QLabel(self.layoutWidget)
        self.uname_in.setObjectName("uname_in")
        self.gridLayout_2.addWidget(self.uname_in, 0, 1, 1, 1)
        self.ucom_in = QtWidgets.QLabel(self.layoutWidget)
        self.ucom_in.setObjectName("ucom_in")
        self.gridLayout_2.addWidget(self.ucom_in, 0, 3, 1, 1)
        self.uid_in = QtWidgets.QLabel(self.layoutWidget)
        self.uid_in.setObjectName("uid_in")
        self.gridLayout_2.addWidget(self.uid_in, 0, 0, 1, 1)
        self.uname_in_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.uname_in_show.setObjectName("uname_in_show")
        self.gridLayout_2.addWidget(self.uname_in_show, 1, 1, 1, 1)
        self.uid_in_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.uid_in_show.setObjectName("uid_in_show")
        self.gridLayout_2.addWidget(self.uid_in_show, 1, 0, 1, 1)
        self.sname_in_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.sname_in_show.setObjectName("sname_in_show")
        self.gridLayout_2.addWidget(self.sname_in_show, 1, 2, 1, 1)
        self.ucom_in_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.ucom_in_show.setObjectName("ucom_in_show")
        self.gridLayout_2.addWidget(self.ucom_in_show, 1, 3, 1, 1)
        self.out_send = QtWidgets.QPushButton(self.centralwidget)
        self.out_send.setGeometry(QtCore.QRect(620, 130, 91, 41))
        self.out_send.setObjectName("out_send")
        self.in_send = QtWidgets.QPushButton(self.centralwidget)
        self.in_send.setGeometry(QtCore.QRect(620, 260, 91, 41))
        self.in_send.setObjectName("in_send")
        self.out_title = QtWidgets.QLabel(self.centralwidget)
        self.out_title.setGeometry(QtCore.QRect(50, 70, 55, 16))
        self.out_title.setObjectName("out_title")
        self.in_title = QtWidgets.QLabel(self.centralwidget)
        self.in_title.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.in_title.setObjectName("in_title")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 100, 551, 95))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sname_out = QtWidgets.QLabel(self.widget)
        self.sname_out.setObjectName("sname_out")
        self.gridLayout.addWidget(self.sname_out, 0, 2, 1, 1)
        self.ucom_out = QtWidgets.QLabel(self.widget)
        self.ucom_out.setObjectName("ucom_out")
        self.gridLayout.addWidget(self.ucom_out, 0, 3, 1, 1)
        self.uname_out = QtWidgets.QLabel(self.widget)
        self.uname_out.setObjectName("uname_out")
        self.gridLayout.addWidget(self.uname_out, 0, 1, 1, 1)
        self.uid_out = QtWidgets.QLabel(self.widget)
        self.uid_out.setObjectName("uid_out")
        self.gridLayout.addWidget(self.uid_out, 0, 0, 1, 1)
        self.uid_out_show = QtWidgets.QTextEdit(self.widget)
        self.uid_out_show.setObjectName("uid_out_show")
        self.gridLayout.addWidget(self.uid_out_show, 1, 0, 1, 1)
        self.uname_out_show = QtWidgets.QTextEdit(self.widget)
        self.uname_out_show.setObjectName("uname_out_show")
        self.gridLayout.addWidget(self.uname_out_show, 1, 1, 1, 1)
        self.ucom_out_show = QtWidgets.QTextEdit(self.widget)
        self.ucom_out_show.setObjectName("ucom_out_show")
        self.gridLayout.addWidget(self.ucom_out_show, 1, 3, 1, 1)
        self.sname_out_show = QtWidgets.QTextEdit(self.widget)
        self.sname_out_show.setObjectName("sname_out_show")
        self.gridLayout.addWidget(self.sname_out_show, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "กองพันที่1"))
        self.com1_title.setText(_translate("MainWindow", "ร้อย 1"))
        self.label_2.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_3.setText(_translate("MainWindow", "จำหน่าย"))
        self.label_4.setText(_translate("MainWindow", "คงเหลือ"))
        self.com2_title.setText(_translate("MainWindow", "ร้อย 2"))
        self.label_7.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_8.setText(_translate("MainWindow", "จำหน่าย"))
        self.label_9.setText(_translate("MainWindow", "คงเหลือ"))
        self.com3_title.setText(_translate("MainWindow", "ร้อย 3"))
        self.label_11.setText(_translate("MainWindow", "ยอดเดิม"))
        self.label_12.setText(_translate("MainWindow", "จำหน่าย"))
        self.label_13.setText(_translate("MainWindow", "คงเหลือ"))
        self.sname_in.setText(_translate("MainWindow", "สกุล"))
        self.uname_in.setText(_translate("MainWindow", "ชื่อ"))
        self.ucom_in.setText(_translate("MainWindow", "กองร้อย"))
        self.uid_in.setText(_translate("MainWindow", "หมายเลข"))
        self.out_send.setText(_translate("MainWindow", "send"))
        self.in_send.setText(_translate("MainWindow", "send"))
        self.out_title.setText(_translate("MainWindow", "นนร.ออก"))
        self.in_title.setText(_translate("MainWindow", "นนร.เข้า"))
        self.sname_out.setText(_translate("MainWindow", "สกุล"))
        self.ucom_out.setText(_translate("MainWindow", "กองร้อย"))
        self.uname_out.setText(_translate("MainWindow", "ชื่อ"))
        self.uid_out.setText(_translate("MainWindow", "หมายเลข"))

    # Click Button
        self.out_send.clicked.connect(self.clickout)
        self.in_send.clicked.connect(self.clickin)

    # Show data Company 1
        # Done
        self.all1.setPlaceholderText(com1all())
        self.active1.setPlaceholderText(com1out())
        self.remain1.setPlaceholderText(com1remain())

    # Show data Company 2
        # Done
        self.all2.setPlaceholderText(com2all())
        self.active2.setPlaceholderText(com2out())
        self.remain2.setPlaceholderText(com2remain())

    # Show data Company 3
        # Done
        self.all3.setPlaceholderText(com3all())
        self.active3.setPlaceholderText(com3out())
        self.remain3.setPlaceholderText(com3remain())

# Function GUI && DATABASE
    def clickout(self):
        print("click out")
        id = self.uid_out_show.toPlainText()
        uname = self.uname_out_show.toPlainText()
        lname = self.sname_out_show.toPlainText()
        com = self.ucom_out_show.toPlainText()
        print(id + uname + lname + com)
        outbatt(id)
        # Show data Company 1
        # Done
        self.all1.setPlaceholderText(com1all())
        self.active1.setPlaceholderText(com1out())
        self.remain1.setPlaceholderText(com1remain())

        # Show data Company 2
        # Done
        self.all2.setPlaceholderText(com2all())
        self.active2.setPlaceholderText(com2out())
        self.remain2.setPlaceholderText(com2remain())

        # Show data Company 3
        # Done
        self.all3.setPlaceholderText(com3all())
        self.active3.setPlaceholderText(com3out())
        self.remain3.setPlaceholderText(com3remain())
    def clickin(self):
        print("click in")
        id = self.uid_in_show.toPlainText()
        uname = self.uname_in_show.toPlainText()
        lname = self.sname_in_show.toPlainText()
        com = self.ucom_in_show.toPlainText()
        print(id + uname + lname + com)
        insertorup(id,uname,lname,com)
        # Show data Company 1
        # Done
        self.all1.setPlaceholderText(com1all())
        self.active1.setPlaceholderText(com1out())
        self.remain1.setPlaceholderText(com1remain())

        # Show data Company 2
        # Done
        self.all2.setPlaceholderText(com2all())
        self.active2.setPlaceholderText(com2out())
        self.remain2.setPlaceholderText(com2remain())

        # Show data Company 3
        # Done
        self.all3.setPlaceholderText(com3all())
        self.active3.setPlaceholderText(com3out())
        self.remain3.setPlaceholderText(com3remain())

# Database
# Done
def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="",
        database="cadet",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb

# Done
def insertin(id,uname,lname,com):
    print("insert in")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'INSERT INTO `batt`(`id`, `name`, `lname`, `com`, `stay`, `outc`) VALUES ({id},"{uname}","{lname}",{com},1,0);'
    print(sql)
    print("Insert into success!!")
    cur.execute(sql)
    db.commit()
    db.close()

# Done
def inbatt(id):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=1,`outc`=0 WHERE id="{id}"'
    print("Check in success!!")
    cur.execute(sql)
    db.commit()
    db.close()

# Done
def outbatt(id):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=0,`outc`=1 WHERE id="{id}"'
    print(sql)
    print("Check out success!!")
    cur.execute(sql)
    db.commit()
    db.close()

# Done
def insertorup(id,uname,lname,com):
    print(id,uname,lname,com)
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT * FROM batt WHERE id="{id}"'
    print("dump databasesuccess!!")
    print(sql)
    cur.execute(sql)
    myresult = cur.fetchall()

    print(myresult)
    if len(myresult) != 0 :
        print("send to inbatt fn")
        inbatt(id)
    else:
        print("send to insert fn")
        insertin(id, uname, lname, com)

def com1all():
    print("com1 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=1'
    print("com1_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com1stay():
    print("com1 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com1out():
    print("com1 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=1'
    print("com1_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com1remain():
    print("com1 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=1'
    print("com1_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com2all():
    print("com2 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=2'
    print("com2_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com2stay():
    print("com2 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com2out():
    print("com2 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=2'
    print("com2_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com2remain():
    print("com2 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=2'
    print("com2_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com3all():
    print("com3 all")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay+outc) FROM `batt` WHERE com=3'
    print("com3_all success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com3stay():
    print("com3 stay")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_stay success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com3out():
    print("com3 out")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(outc) FROM `batt` WHERE com=3'
    print("com3_out success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

def com3remain():
    print("com3 remain")
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'SELECT SUM(stay) FROM `batt` WHERE com=3'
    print("com3_remain success!!")
    cur.execute(sql)
    myresult = cur.fetchall()
    x = str(myresult[0][0])
    return x

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())