# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\EP\Check_Cadet_2\ui\outbatt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_OutbattWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 217)
        MainWindow.setStyleSheet("background-color: rgb(255, 98, 98);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 551, 98))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sname_out = QtWidgets.QLabel(self.layoutWidget)
        self.sname_out.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.sname_out.setObjectName("sname_out")
        self.gridLayout.addWidget(self.sname_out, 0, 2, 1, 1)
        self.ucom_out = QtWidgets.QLabel(self.layoutWidget)
        self.ucom_out.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.ucom_out.setObjectName("ucom_out")
        self.gridLayout.addWidget(self.ucom_out, 0, 3, 1, 1)
        self.uname_out = QtWidgets.QLabel(self.layoutWidget)
        self.uname_out.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.uname_out.setObjectName("uname_out")
        self.gridLayout.addWidget(self.uname_out, 0, 1, 1, 1)
        self.uid_out = QtWidgets.QLabel(self.layoutWidget)
        self.uid_out.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.uid_out.setObjectName("uid_out")
        self.gridLayout.addWidget(self.uid_out, 0, 0, 1, 1)
        self.uid_out_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.uid_out_show.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.uid_out_show.setObjectName("uid_out_show")
        self.gridLayout.addWidget(self.uid_out_show, 1, 0, 1, 1)
        self.uname_out_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.uname_out_show.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"")
        self.uname_out_show.setObjectName("uname_out_show")
        self.gridLayout.addWidget(self.uname_out_show, 1, 1, 1, 1)
        self.ucom_out_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.ucom_out_show.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.ucom_out_show.setObjectName("ucom_out_show")
        self.gridLayout.addWidget(self.ucom_out_show, 1, 3, 1, 1)
        self.sname_out_show = QtWidgets.QTextEdit(self.layoutWidget)
        self.sname_out_show.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.sname_out_show.setObjectName("sname_out_show")
        self.gridLayout.addWidget(self.sname_out_show, 1, 2, 1, 1)
        self.out_title = QtWidgets.QLabel(self.centralwidget)
        self.out_title.setGeometry(QtCore.QRect(30, 10, 141, 16))
        self.out_title.setObjectName("out_title")
        self.out_send = QtWidgets.QPushButton(self.centralwidget)
        self.out_send.setGeometry(QtCore.QRect(600, 70, 91, 41))
        self.out_send.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.out_send.setObjectName("out_send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sname_out.setText(_translate("MainWindow", "สกุล"))
        self.ucom_out.setText(_translate("MainWindow", "กองร้อย"))
        self.uname_out.setText(_translate("MainWindow", "ชื่อ"))
        self.uid_out.setText(_translate("MainWindow", "หมายเลข"))
        self.out_title.setText(_translate("MainWindow", "นนร.ออก"))
        self.out_send.setText(_translate("MainWindow", "send"))

        self.out_send.clicked.connect(self.clickout)
        
        
    def clickout(self):
        print("click out")
        id = self.uid_out_show.toPlainText()
        uname = self.uname_out_show.toPlainText()
        lname = self.sname_out_show.toPlainText()
        com = self.ucom_out_show.toPlainText()
        print(id + uname + lname + com)
        outbatt(id)    

def ConnectorMysql():
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="12341234",
        database="testdb",
        # auth_plugin='mysql_native_password'
    )
    print('Connect Database Successful')
    return mydb

def outbatt(id):
    db = ConnectorMysql()
    cur = db.cursor()
    sql = f'UPDATE `batt` SET `stay`=0,`outc`=1 WHERE id="{id}"'
    print(sql)
    print("Check out success!!")
    cur.execute(sql)
    db.commit()
    db.close()        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_OutbattWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
